services:
  qf_node:
    image: andor/qf-node:997f600
    container_name: qf_node
    volumes:
      - ./data:/data
    ports:
      - 9944:9944
      - 30334:30334
      - 9615:9615
    restart: unless-stopped
    command:  >
      ./qf-node
      --chain=qf-devnet
      --base-path /data
      --prometheus-external
      --prometheus-port 9615

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/home/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/home/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:9.4.7
    user: ":"
    ports:
      - "80:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards
      - ./grafana/alerts.yml:/etc/grafana/provisioning/alerting/alerts.yml
      - ./grafana/alertmanager.json:/etc/grafana/provisioning/alerting/alertmanager.json
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped