{
 "title": "Substrate Node Metrics",
 "description": "An updated version of \"My Polkadot Metrics\" Grafana dashboard.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_block_height", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Networking Bytes Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Finality Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(\n  substrate_block_height{\n    chain=\"qf-devnet\",\n    instance=\"qf_node:9615\",\n    job=\"qf_node\",\n    status=\"best\"\n  }\n) - on(chain, instance, job) (\n  substrate_block_height{\n    chain=\"qf-devnet\",\n    instance=\"qf_node:9615\",\n    job=\"qf_node\",\n    status=\"finalized\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total[1m]) - rate(substrate_tasks_polling_duration_count[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Cache DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "substrate_database_cache_bytes", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Peers connected & discovered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Peers count"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered",
     "legendFormat": "Discovered peers"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "substrate_sync_peers" }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "substrate_sync_queued_blocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocks processed by import queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_import_queue_processed_total",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "substrate_number_leaves", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Extra Justifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sync_extra_justifications",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}